# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelectToCart():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(60)
        return self.driver

    def teardown_method(self, method):
        self.driver.quit()

# This may not qualify as a Page Object. This is more like a test object or a test path.
# More test paths could be added to this class
    def test_our_products(self):
        list = []
        self.driver.get("https://www.advantageonlineshopping.com/")
        self.driver.set_window_size(1052, 605)
        self.driver.find_element(By.ID, "speakersImg").click()
        list.append("SpeakersIMG category selected.")
        self.driver.find_element(By.ID, "accordionAttrib1").click()
        self.driver.find_element(By.ID, "manufacturer_2").click()
        self.driver.find_element(By.LINK_TEXT, "Logitech X100 Speaker System - Wireless Speaker(s)").click()
        self.driver.find_element(By.NAME, "save_to_cart").click()
        self.driver.find_element(By.ID, "checkOutPopUp").click()
        list.append("Logitech speaker product selected.")
        for i in range(5):
            try:
                self.driver.find_element(By.CSS_SELECTOR, "article").click()
                break
            except Exception as e:
                print(e)
                time.sleep(1)

        self.driver.find_element(By.ID, "checkOutPopUp").click()
        list.append("Checkout request in progress.")
        self.driver.find_element(By.CSS_SELECTOR, "li > #toolTipCart .removeProduct").click()
        self.driver.close()
        list.append("Product removal request completed.")
        return list
