# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.common.exceptions import ElementClickInterceptedException, NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


def get_company(brand):
    if brand == "manufacturer_0":
        company = "Bose"
    elif brand == "manufacturer_1":
        company = "HP"
    elif brand == "manufacturer_2":
        company = "Logitech"
    else:
        company = "Company not selected"
    return company


class TestSelectToCart2():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(60)
        return self.driver

    def teardown_method(self, method):
        self.driver.quit()

    # This may not qualify as a Page Object. This is more like a test object or a test path.
# More test paths could be added to this class
    def test_our_products(self, category, brand, display):
        list = []
        if brand != "":
            company = get_company(brand)
        self.driver.get("https://www.advantageonlineshopping.com/")
        self.driver.maximize_window()
        self.driver.find_element(By.ID, category).click()
        list.append("Category selected: " + category)
        if brand != "":
            self.driver.find_element(By.ID, "accordionAttrib1").click()
            self.driver.find_element(By.ID, brand).click()
            list.append("Company name: " + company)
        elif display != "":
            self.driver.find_element(By.ID, "accordionAttrib0").click()
            self.driver.find_element(By.NAME, display).click()
            label = self.driver.find_element(By.CSS_SELECTOR, "label[for='" + display + "']").text
            list.append("Display type: " + label)
        else:
            print("Unknown value passed to test our products method.")
            exit(1)
        for i in range(5):
            try:
                product = self.driver.find_element(By.XPATH, "(//div/ul/li/p[1]/a[@class='productName ng-binding'])")
                list.append("Product name: " + product.text)
                self.driver.find_element(By.XPATH, "//li[@class='ng-scope']/img[1]").click()
                break
            except Exception as e:
                print(e)

        for i in range(5):
            try:
                self.driver.find_element(By.NAME, "save_to_cart").click()
                break
            except Exception as e:
                print(e)
                time.sleep(2)

        self.driver.find_element(By.ID, "checkOutPopUp").click()
        list.append("Product selected: First in list")

        for i in range(5):
            try:
                self.driver.find_element(By.CSS_SELECTOR, "article").click()
                break
            except Exception as e:
                print(e)
                time.sleep(1)

        self.driver.find_element(By.ID, "checkOutPopUp").click()
        self.driver.find_element(By.CSS_SELECTOR, "li > #toolTipCart .removeProduct").click()
        self.driver.close()
        list.append("Product removal request completed.")
        return list

