# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOSC1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_oSC1(self):
    self.driver.get("https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/cart/webapp/index.html")
    self.driver.set_window_size(1182, 637)
    self.driver.find_element(By.ID, "container-cart---homeView--page-intHeader-BarPH").click()
    self.driver.find_element(By.ID, "container-cart---homeView--searchField-I").click()
    self.driver.find_element(By.ID, "container-cart---homeView--searchField-search").click()
    self.driver.find_element(By.ID, "container-cart---homeView--searchField-I").send_keys("Astro")
    # Product Catalog Header
    self.driver.find_element(By.ID, "__item0-container-cart---homeView--productList-0-titleText-inner").click()

    self.driver.find_element(By.ID, "container-cart---category--page-navButton-iconBtn").click()
    self.driver.find_element(By.ID, "container-cart---homeView--searchField-reset").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\__item1-container-cart---homeView--categoryList-7-content .sapMSLITitleOnly").click()
    self.driver.find_element(By.ID, "__item5-container-cart---category--productList-0-titleText-inner").click()
    self.driver.find_element(By.ID, "__item5-container-cart---category--productList-0-titleText-inner").click()
    self.driver.find_element(By.ID, "__item5-container-cart---category--productList-1-titleText-inner").click()
    self.driver.find_element(By.ID, "__button10-BDI-content").click()
    self.driver.find_element(By.ID, "__button9-img").click()
    self.driver.find_element(By.ID, "__button9-img").click()
    self.driver.find_element(By.ID, "__button9-img").click()
    self.driver.find_element(By.ID, "container-cart---cartView--editButton-img").click()
    element = self.driver.find_element(By.ID, "__item7-container-cart---cartView--entryList-0-imgDel")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "__item7-container-cart---cartView--entryList-0-imgDel-img").click()
    self.driver.find_element(By.ID, "__mbox-btn-0-BDI-content").click()
    self.driver.find_element(By.ID, "__item7-container-cart---cartView--entryList-0-imgDel-img").click()
    self.driver.find_element(By.ID, "__mbox-btn-2-BDI-content").click()
    self.driver.find_element(By.ID, "container-cart---cartView--entryList-nodata-text").click()
    self.driver.find_element(By.ID, "__button9-img").click()
    self.driver.close()
  
