# Generated by Selenium IDE for Chrome Browser
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSDAUAIDE1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sDAUAIDE1(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(1102, 602)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-price\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").click()

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-price\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-price\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys("Walter")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys("Beasly")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys("70122")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"payment-info-value\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"total-label\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()

    self.driver.find_element(By.ID, "react-burger-menu-btn").click()

    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"logout-sidebar-link\"]").click()
  
