# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://demo.opencart.com/admin/index.php?route=common/login")
    self.driver.set_window_size(1188, 688)
    element = EC.presence_of_element_located((By.ID, "input-username"))
    WebDriverWait(self.driver, 30).until(element)
    self.driver.find_element(By.ID, "input-username").click()
    self.driver.find_element(By.ID, "input-username").send_keys("demo")
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("demo")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(4)
    print("Display Dashboard")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-close").click()
    print("Close popup window")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#header-logout .d-none").click()
    print("Logged out of Opencart")
  
